[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.29'

remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/'
]
